### ISSUE TITLE
Is this a typo?

### ISSUE THREAD

**Issue by wenyang-li** [HERA-Team/heracal#27]
In heracal/heracal/firstcal.py, line 52: d12_wgt = np.sum(w1 * w1, axis=0).reshape(1, -1)
Should it be d12_wgt = np.sum(w1 * w2, axis=0).reshape(1, -1)?

**Comment by plaplant** [comment]
Yes, I think it should be. I'm working on overhauling the firstcal module right now, and I'll include this update in the fix. Thanks!

**Comment by plaplant** [comment]
This change was made as part of PR #26
